//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class REVIEWRATING
    {
        public int ID { get; set; }
        public Nullable<int> MASANPHAM { get; set; }
        public Nullable<int> MATAIKHOAN { get; set; }
        public string HOTEN { get; set; }
        public string NOIDUNG { get; set; }
        public System.DateTime THOIGIANDANG { get; set; }
        public Nullable<double> SOSAODANHGIA { get; set; }
    
        public virtual SANPHAM SANPHAM { get; set; }
    }
}
