//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SANPHAM
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SANPHAM()
        {
            this.CHITIETDONHANGs = new HashSet<CHITIETDONHANG>();
            this.REVIEWRATINGs = new HashSet<REVIEWRATING>();
        }
    
        public int MASP { get; set; }
        public int MANCC { get; set; }
        public int MAKM { get; set; }
        public string TENSP { get; set; }
        public int LOAISP { get; set; }
        public int SOLUONG { get; set; }
        public Nullable<bool> TINHTRANG { get; set; }
        public string KICHTHUOC { get; set; }
        public string MAUSAC { get; set; }
        public string THONGTIN { get; set; }
        public decimal GIABAN { get; set; }
        public System.DateTime NGAYTHEM { get; set; }
        public System.DateTime NGAYCAPNHAT { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CHITIETDONHANG> CHITIETDONHANGs { get; set; }
        public virtual KHUYENMAI KHUYENMAI { get; set; }
        public virtual LOAISANPHAM LOAISANPHAM { get; set; }
        public virtual NHACUNGCAP NHACUNGCAP { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<REVIEWRATING> REVIEWRATINGs { get; set; }
    }
}
